kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "acm-robot-test-pvc"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: $STORAGE_CLASS_NAME