{{/*
# ******************************************************************************
#  Copyright (C) 2022 Ericsson Software Technology
#
# The copyright to the computer program(s) herein is the property of
# Ericsson Software Technology. The programs may be used and/or copied
# only with written permission from Ericsson Software Technology or in
# accordance with the terms and conditions stipulated in the
# agreement/contract under which the program(s) have been supplied.
# ******************************************************************************
*/}}

{{- if eq "true" (include "eric-oss-acm-runtime.log-streaming-activated" .) }}
  {{- include "eric-log-shipper-sidecar.logshipper-sidecar-configmap" . }}
{{- end }}