{{/*
# ******************************************************************************
#  Copyright (C) 2022 Ericsson Software Technology
#
# The copyright to the computer program(s) herein is the property of
# Ericsson Software Technology. The programs may be used and/or copied
# only with written permission from Ericsson Software Technology or in
# accordance with the terms and conditions stipulated in the
# agreement/contract under which the program(s) have been supplied.
# ******************************************************************************
*/}}

{{- if .Values.global -}}
  {{- if .Values.global.security -}}
    {{- if .Values.global.security.policyBinding -}}
      {{- if .Values.global.security.policyBinding.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
  {{- include "eric-oss-acm-runtime.labels" . | nindent 4 }}
  annotations:
  {{- include "eric-oss-acm-runtime.annotations" . | nindent 4 }}
  name: {{ template "eric-oss-acm-runtime.name" . }}-security-policy-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "eric-oss-acm-runtime.securityPolicy.reference" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "eric-oss-acm-runtime.name" . }}-sa
      {{- end -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
