{{/*
# ******************************************************************************
#  Copyright (C) 2022 Ericsson Software Technology
#
# The copyright to the computer program(s) herein is the property of
# Ericsson Software Technology. The programs may be used and/or copied
# only with written permission from Ericsson Software Technology or in
# accordance with the terms and conditions stipulated in the
# agreement/contract under which the program(s) have been supplied.
# ******************************************************************************
*/}}

{{- if .Values.global -}}
{{- if and .Values.global.networkPolicy .Values.networkPolicy -}}
{{- if and .Values.networkPolicy.enabled .Values.global.networkPolicy.enabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ template "eric-oss-acm-runtime.name" . }}-allow-self-ingress
  labels:
  {{- include "eric-oss-acm-runtime.labels" . | nindent 4 }}
  annotations:
  {{- include "eric-oss-acm-runtime.annotations" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{  include "eric-oss-acm-runtime.name" . }}
  policyTypes:
    - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{  include "eric-oss-acm-runtime.name" . }}
    ports:
      - port: 6969
        protocol: TCP
{{- end }}
{{- end }}
{{- end }}
